dkqpeowkd/SSDproject

SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/packages.config
SSD/src/main.cpp
SSD/test/test_main.cpp
SSDProject.sln
TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/packages.config
TestShell/src/main.cpp
TestShell/test/test_main.cpp

1. test의 main과 실제 코드의 main함수들이 충돌 나지 않도록 build별로 구성을 달리 했습니다.

build configure test/release added

---

SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h

1. SsdInerface Class(SsdInerface.h, SsdInerface.cpp)를 추가 했습니다

SsdInterface class added

---

SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters

1. VS filter에 SsdInterface 클래스 파일들 추가했습니다.

visual studio configure added

---

BA_code_convention.md
SSD/SSD.vcxproj
SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h
SSD/ssd_output.txt
SSD/test/test_main.cpp
TestShell/TestShell.vcxproj

1. output file이 없으면 생기는지 check하는 TC를 추가했습니다.
2. cpp 17을 표준으로 설정하는 main 브랜치를 pull했습니다.

output file check TC added

---

SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h
SSD/test/test_main.cpp

Write pass / fail TC 통과했습니다.
ssd_nand.txt 에 저장 후 output에는 아무 업데이트 하지 않습니다.
data 정상적으로 기록된 것 확인했습니다.
lba나 datapattern이 잘 못 입력된 경우 error return 합니다.

[GREEN] Write Pass TC pass

---

SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h
SSD/src/SsdType.h
SSD/test/test_main.cpp

NAND Read 기능 구현했습니다.
Read 및 Unmap read TC 통과 확인했습니다

[GREEN] NAND Read 구현 및 TC pass

---

SSD/src/main.cpp

1. SSD Command를 받을때 소문자도 입력받을 수 있게끔 처리했습니다.

SSD command를 받을때 소문자도 가능하게 처리

---

TestShell/ReadCommand.h
TestShell/test/test_main.cpp

- Google Mock을 활용해 callSystem(), readOutput() 함수 모킹 처리
- 실제 ssd.exe 실행 없이도 TestShell 명령어 동작을 검증할 수 있음
- read, write, fullwrite, fullread 등 명령어에 대한 단위 테스트 기반 마련

MockTestShell 추가

---

TestShell/test/test_main.cpp

-Add Unit TC (Write 9+ Read 9 + FullWrite 1 + FullRead 1)

[Add] test_main.cpp

---

TestShell/src/main.cpp

[Modify] main-TestShell

---

SSD/src/SsdInterface.cpp

NAND file initialize 추가

---

TestShell/HelpCommand.cpp
TestShell/HelpCommand.h
TestShell/TestShell.cpp
TestShell/TestShell.h
TestShell/src/main.cpp
TestShell/test_TestShellMain.cpp

Merge branch 'feature/testshellmain' into feature/testshell_mainloop
update help command, and getting input from console prompt
add help command with TC

Merge Feature/testshell_mainloop to feature/testshell_main

---

TestShell/TestShell.cpp
TestShell/TestShell.h
TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/src/main.cpp

[ADD] 1st Release (TestSheel Project)

---

SSD/src/NandStorage.cpp
SSD/src/NandStorage.h

1. [refactor] typo and const reference added

[refactor] typo and const reference added

---

SSD/test/test_main.cpp

Buffer 기능 관련 UnitTest 추가
부족하거나 잘못된 TC 있는지 검토부탁드립니다.

[RED] Buffer 기능 관련 UnitTest 추가

---

SSD/src/NandStorage.cpp
SSD/src/NandStorage.h
SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h
SSD/test/test_main.cpp

1. Erase TC를 추가했습니다.
2. interface와 stroage에 dummy erase function을 추가했습니다.

[RED] Erase TC를 추가했습니다.

---

TestShell/TestShell.h

header파일에 include 추가

---

SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/src/CommandBuffer.cpp
SSD/src/CommandBuffer.h
SSD/src/SsdInterface.h
SSD/test/CommandBufferTest.cpp
SSD/test/test_main.cpp

1. Command Buffer TC가 몇가지 추가 되었습니다.
2. Command Buffer TC를 파일을 따로 추가하였습니다.
3. CommandBuffer object가 추가 되었습니다.

[RED] Command Buffer TC added And CommandBuffer Object created

---

SSD/src/NandStorage.cpp
SSD/src/NandStorage.h
SSD/src/SsdInterface.cpp

file 생성/접근/수정 등이 안되면 error return 되도록 수정

[REFACTOR] File에 대한 Exception handling 추가

---

SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h

SsdInterface에서 commandBuffer 호출하는 부분 작성했습니다.

commandBuffer 호출 구현

---

SSD/src/CommandBuffer.cpp
SSD/src/CommandBuffer.h
SSD/test/CommandBufferTest.cpp

1. CommandBuffer에서 Read하면 buffer폴더에서 filename을 불러와서 commandBuffers를 만듭니다.
2. commandBuffers에서 LBA Map을 만들어서 주소와 value를 W,E에 따라 저장합니다.
3. Read한 LBA주소가 map에 있으면 Value를 반환하고 없으면 pre defined된 스트링을 반환합니다.

[GREEN] SSD INTERFACE read enabled

---

SSD/src/CommandBuffer.cpp
SSD/src/CommandBuffer.h
SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h
SSD/src/SsdType.h

중복사용 메세지 정리
buffer full 확인하는 코드 중복사용되어 따로 함수 분리

[REFACTOR] 코드정리

---

SSD/src/CommandBuffer.cpp
SSD/src/CommandBuffer.h
SSD/test/CommandBufferTest.cpp

[refactor] command buffer의 안쓰는 함수를 정리했습니다.

[refactor] command buffer의 안쓰는 함수를 정리했습니다.

---

SSD/src/CommandBuffer.cpp
SSD/src/SsdInterface.cpp
SSD/src/SsdInterface.h
SSD/src/SsdType.h
SSD/test/CommandBufferTest.cpp
SSD/test/test_main.cpp

1. commandBuffer 생성할때 init or getCommands를 하게끔 수정했습니다.
2. command에서 불러올때 1_, 2_ 는 빼고 command 만 저장하게 했습니다.

[Green] Command buffer TC fixed

---

TestShell/ExitCommand.h
TestShell/FullReadCommand.h
TestShell/FullWriteCommand.h
TestShell/HelpCommand.h
TestShell/Log.cpp
TestShell/Log.h
TestShell/ReadCommand.h
TestShell/TestShell.h
TestShell/TestShell.vcxproj
TestShell/TestShell.vcxproj.filters
TestShell/WriteCommand.h

[ADD] Logger Class
- Log Message 출력 예시 (logMessage("class명","Message")) ex : logMessage("WriteCommand::Execute", "test");
- Log 객체 Injection 방식으로 사용 유무 결정 writeCommand = make_shared(); writeCommand = make_shared(&log);

[ADD] Logger Class , [Modify] C++ 17 적용, 전처리기 _CRT_SECURE_NO_WARNINGS 적용

---

SSD/test/CommandBufferTest.cpp

아래 TC 시나리오 추가했습니다.
W->E ignore 시나리오 1개
E->W ignore 시나리오 3개
E->E merge 시나리오 3개
E->E merge 안되는 시나리오 1개

[RED] Command Buffer Ignore/Merge TC 추가

---

SSD/test/CommandBufferTest.cpp

1. 여러 buffer들을 하나로 합치는 TC를 추가했습니다.

Multiple buffer TC added

---

SSD/src/CommandBuffer.cpp
SSD/test/CommandBufferTest.cpp

WtoE ignore case 기존 TC pass
WtoE ignore case TC 추가 및 pass
ProcessWrite/Erase 안에서 vector push 하게 AddBuffer 변경

[GREEN] WtoE ignore case 구현 완료

---

SSD/src/CommandBuffer.cpp

1. E가 하나 기존에 있을때 W가 같은 LBA에 오게되면 덮어 쓸수 있게 만들었습니다.

EToW feature eanbled

---

TestShell/ExitCommand.h
TestShell/FullReadCommand.h
TestShell/FullWriteCommand.h
TestShell/HelpCommand.h
TestShell/Log.cpp
TestShell/Log.h
TestShell/ReadCommand.cpp
TestShell/ReadCommand.h
TestShell/WriteCommand.h

- Log 메세지 가변인자 추가
- Read Command에서 Expected Pattern를 인자로 줬을 경우 Compare 하는 로직 추가

[Modify] Log 및 Read Command 

---

SSD/SSD.vcxproj
SSD/SSD.vcxproj.filters
SSD/src/Command.cpp
SSD/src/Command.h
SSD/src/CommandBuffer.cpp
SSD/src/CommandBuffer.h
SSD/src/CommandFactory.cpp
SSD/src/CommandFactory.h
SSD/src/SsdController.cpp
SSD/test/CommandBufferTest.cpp

1. command buffer에 Factory pattern 및 Command pattern 적용했습니다. 
2. NandStorage는 ExecuteNandStorage, CommandBuffer는 ApplyCommandBuffer 함수로 Command 객체에서 각각 처리하게 진행했습니다.

command buffer에 Factory pattern 및 Command pattern 적용했습니다. 

---

SSD/src/CommandBuffer.cpp
SSD/src/CommandBuffer.h
SSD/src/SsdController.cpp
SSD/src/SsdController.h

SsdController가 CommandBuffer의 Commands와 Buffer 개수 가져오지 않게 수정

[REFACTOR] SsdController와 CommandBuffer 간 의존성 낮춤
